# Language: "ru" or "en"
lang: "ru"

# Сопоставление ролей с правами доступа (для отображения роли в Tab и статус-баре)
# Игроку будет присвоена первая роль из списка, на которую у него есть право (permission).
role-permissions:
  admin: "serverutils.role.admin"
  detective: "serverutils.role.detective"
  banker: "serverutils.role.banker"
  judge: "serverutils.role.judge"
  mayor: "serverutils.role.mayor"
