# Language: "ru" or "en"
lang: "ru"

# Включение и отключение функций плагина
features:
  elytra-end-restriction: true     # Запрет полетов на элитрах в Энде
  anvil-repair: true               # Ремонт наковален железными блоками
  door-knocking: true              # Стук в деревянные двери (Shift + ЛКМ)
  enderman-pickup-protection: true # Запрет эндерменам переносить блоки
  item-signing: true               # Подпись предметов пером (Shift + ПКМ)
  item-lock-protection: true       # Защита заблокированных артов/книг от копирования
  tab-formatter: true              # Форматирование списка игроков (Tab)
  hide-nametags: true              # Скрытие никнеймов над головой игроков
  recipes:
    invisible-frame: true          # Крафт невидимой рамки
    invisible-light: true          # Крафт невидимого источника света
    debug-stick: true              # Крафт отладочной палки (Debug Stick)


# Сопоставление ролей с правами доступа (для отображения роли в Tab и статус-баре)
# Игроку будет присвоена первая роль из списка, на которую у него есть право (permission).
role-permissions:
  admin: "serverutils.role.admin"
  detective: "serverutils.role.detective"
  banker: "serverutils.role.banker"
  judge: "serverutils.role.judge"
  mayor: "serverutils.role.mayor"

# Кастомные Shaped рецепты крафта
custom-recipes:
  saddle:
    enabled: true
    result:
      type: "SADDLE"
      amount: 1
      name: "&eСамодельное седло"
      lore:
        - "&7Создано из качественной кожи"
        - "&7и прочных нитей."
    shape:
      - "LLL"
      - "S S"
      - "   "
    ingredients:
      L: "LEATHER"
      S: "STRING"
